<a href="https://colab.research.google.com/github/DinhQuocTuan0108/Bai-tap/blob/main/Buoi5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[0,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test=[[0.2,0.5],[0.3,0.2],[0,0.5],[0.5,1]]
y_test=model.predict(x_test)
print(y_test)

Do chinh xac 1.0
[1 0 0 1]


In [8]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[0.5,0.5],[0.3,-0.5],[-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
print('Do chinh xac',model.score(x,y))
x_test=[[0,0],[0,1],[1,0],[1,1]]
y_test=model.predict(x_test)
print(y_test)

Do chinh xac 0.5
[0 0 0 0]


In [31]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
data=pd.read_csv('data_crab.csv')
data['sex'].replace('M,1')
data['sex'].replace('F,0')
x=data.drop(['sp','sex'],axis=True)
y=data['sex']

model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))

do chinh xac 0.505


In [32]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url='/content/data_crab.csv'
data= pd.read_csv(url)
#data=data.set_index(data['sp'])
data.loc[data['sex']=='M','sex']='1'
data.loc[data['sex']=='F','sex']='0'
data[(data['sp']=='B')]
x=data.drop(['sp','sex'],axis=True)    #bo di loài, giới tính
y=data['sex']#giới tính
model=Perceptron()
model.fit(x,y)
print('độ chính xác',model.score(x,y))
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)
x_test = [[5,6,14,13,10,6],[8,12,7,23,30,15],[13,5,22,15,10,13],[19,12,15,20.3,11.5,22.6]] 
y_test = model.predict(x_test)
print(y_test)


độ chính xác 0.505
['0' '1' '0' '0']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [35]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "data_crab.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[0,1,2]], axis=1)
y = data["sex"].replace(["M","F"],[1,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[6,7,15,18.2,7], [6.6,5.5,17.4,20.4,2.7]]
y_pred = model.predict(x_input)

print(y_pred)

Độ chính xác:  0.8785714285714286
[0 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [40]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd

url = "iris.csv"
data = pd.read_csv(url)
x = data.drop(data.columns[[4]],axis=1)
y = data["variety"].replace(["Setosa","Versicolor","Virginica"],[1,0,0])

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

model = Perceptron()
model.fit(x_train, y_train)
print("Độ chính xác: ", model.score(x_train,y_train))

x_input = [[6,2.2,1.5,0.8], [6.6,3.5,1.4,0.7],[5.5,2,1.3,1]]
y_pred = model.predict(x_input)

print(y_pred)

Độ chính xác:  1.0
[1 1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
